name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
    env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
    - run: |
        docker login -u $DOCKER_USERNAME -p $secrets.DOCKERHUB_TOKEN 
    - name: Build the Docker image
      run: docker build -t udagram-api-feed ./udagram-api-feed
    - name: Build the Docker image   
      run: docker build -t udagram-api-user ./udagram-api-user
    - name: Build the Docker image   
      run: docker build -t udagram-frontend ./udagram-frontend
    - name: Build the Docker image  
      run: docker build -t udagram-reverseproxy ./udagram-reverseproxy
      
    - name: Docker Push
      run: docker push mubarak23/udagram-api-feed
    - name: Docker Push   
      run: docker push mubarak23/udagram-api-user
    - name: Docker Push  
      run: docker push mubarak23/udagram-frontend
    - name: Docker Push  
      run: docker push mubarak23/udagram-reverseproxy 