name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $secrets.DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build -t udagram-api-feed ./udagram-api-feed
           docker build -t udagram-api-user ./udagram-api-user
           docker build -t udagram-frontend ./udagram-frontend
           docker build -t udagram-reverseproxy ./udagram-reverseproxy
      
    - name: Docker Push
      run: docker push mubarak23/udagram-api-feed
           docker push mubarak23/udagram-api-user
           docker push mubarak23/udagram-frontend
           docker push mubarak23/udagram-reverseproxy 